//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dictionary2020 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dictionary2020.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aa
        ///aah
        ///aahed
        ///aahing
        ///aahs
        ///aal
        ///aalii
        ///aaliis
        ///aals
        ///aardvark
        ///aardvarks
        ///aardwolf
        ///aardwolves
        ///aargh
        ///aarrgh
        ///aarrghh
        ///aas
        ///aasvogel
        ///aasvogels
        ///ab
        ///aba
        ///abaca
        ///abacas
        ///abaci
        ///aback
        ///abacterial
        ///abacus
        ///abacuses
        ///abaft
        ///abaka
        ///abakas
        ///abalone
        ///abalones
        ///abamp
        ///abampere
        ///abamperes
        ///abamps
        ///abandon
        ///abandoned
        ///abandoner
        ///abandoners
        ///abandoning
        ///abandonment
        ///abandonments
        ///abandons
        ///abapical
        ///abas
        ///abase
        ///abased
        ///abasedly
        ///abasement
        ///abasements
        ///abaser
        ///abasers
        ///abases
        ///abash
        ///abashed
        ///abashedly
        ///abashes
        ///abashing
        ///abashment
        ///abashments
        ///abasia
        ///abasias
        ///abasing
        ///abatabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dictionary {
            get {
                return ResourceManager.GetString("Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///A-  prefix (also an- before a vowel sound) not, without (amoral). [greek]
        ///
        ///Aa  abbr. 1 automobile association. 2 alcoholics anonymous. 3 anti-aircraft.
        ///
        ///Aardvark  n. Mammal with a tubular snout and a long tongue, feeding on termites. [afrikaans]
        ///
        ///Ab-  prefix off, away, from (abduct). [latin]
        ///
        ///Aback  adv.  take aback surprise, disconcert. [old english: related to *a2]
        ///
        ///Abacus  n. (pl. -cuses) 1 frame with wires along which beads are slid for calculating. 2 archit. Flat slab on top of a capital. [latin from [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OxfordEnglishDictionary {
            get {
                return ResourceManager.GetString("OxfordEnglishDictionary", resourceCulture);
            }
        }
    }
}
